import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../server/worker.mjs';
function fixture(){const memory=new Map(),reads=[],writes=[];return {memory,reads,writes,env:{KADETTEN_OWNER_EMAIL:'owner@example.test',KADETTEN_AUTH_PROVIDER:'sites',KADETTEN_SITES_ORIGIN:'https://kadetten.example.chatgpt.site',BUCKET:{get:async key=>{reads.push(key);return memory.has(key)?{json:async()=>JSON.parse(memory.get(key))}:null},put:async(key,value)=>{writes.push(key);memory.set(key,value)}}}}}
test('Public writes are rejected before storage or body access',async()=>{const f=fixture();const r=await worker.fetch(new Request('https://app.test/api/refresh',{method:'POST',body:'{}'}),f.env);assert.equal(r.status,403);assert.deepEqual(f.reads,[]);assert.deepEqual(f.writes,[])});
test('Public access does not grant update permission',async()=>{const f=fixture();const r=await worker.fetch(new Request('https://app.test/api/access'),f.env);assert.deepEqual(await r.json(),{canUpdate:false})});
test('Full articles are read separately, missing articles and writes rejected',async()=>{const f=fixture(),version='a'.repeat(64);f.memory.set('kadetten/current.json',JSON.stringify({stories:[{id:'example',articleVersion:version}]}));f.memory.set('kadetten/articles/example/'+version+'.json',JSON.stringify({id:'example',version,html:'<p>Complete article</p>'}));let r=await worker.fetch(new Request('https://app.test/api/articles/example?v='+version),f.env);assert.equal(r.status,200);assert.equal((await r.json()).html,'<p>Complete article</p>');r=await worker.fetch(new Request('https://app.test/api/articles/missing'),f.env);assert.equal(r.status,404);r=await worker.fetch(new Request('https://app.test/api/articles/example',{method:'POST'}),f.env);assert.equal(r.status,405);assert.equal(f.writes.length,0)});
test('Bad automation credentials never authorize writes',async()=>{const f=fixture();f.env.KADETTEN_UPDATE_KEY_SHA256='0'.repeat(64);const r=await worker.fetch(new Request('https://app.test/api/refresh',{method:'POST',headers:{'X-Kadetten-Update-Key':'wrong'},body:'{}'}),f.env);assert.equal(r.status,403);assert.equal(f.writes.length,0)});
test('Cross-origin owner write is rejected',async()=>{const f=fixture();const r=await worker.fetch(new Request('https://kadetten.example.chatgpt.site/api/refresh',{method:'POST',headers:{Origin:'https://other.test','oai-authenticated-user-id':'verified-platform-id','oai-authenticated-user-email':'owner@example.test'},body:'{}'}),f.env);assert.equal(r.status,403);assert.equal(f.reads.length,0)});
