import test from 'node:test';
import assert from 'node:assert/strict';
import {previews,fixtureKey} from '../server/previews.mjs';
import {publicReadCors} from '../server/cors.mjs';
const game={id:'test',home:'Kadetten Schaffhausen',away:'Opponent',date:'2099-01-01',time:'18:45',league:'EHL',venue:'Arena'};
const record={club:'kadetten',id:'test',fixtureKey:fixtureKey(game),headline:'Ein Heimspiel mit Kontext',paragraphs:['Eine bestätigte Information über diese Partie und den Wettbewerb.','Weitere bestätigte Informationen zur Form der beiden Mannschaften.'],sources:[{label:'Vereinsquelle',url:'https://kadettensh.ch/'}],generatedAt:new Date().toISOString()};
function setup(){const data=new Map([['kadetten/current.json',{games:[game]}]]);const env={BUCKET:{get:async k=>data.has(k)?{json:async()=>data.get(k)}:null,put:async(k,v)=>data.set(k,JSON.parse(v))}};return {data,env}}
async function post(env,p=record){const token='test-secret';env.KADETTEN_UPDATE_KEY_SHA256=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))).toString('hex');return previews(new Request('https://service.test/api/previews',{method:'POST',headers:{'X-Kadetten-Update-Key':token},body:JSON.stringify({previews:[p]})}),env)}
test('Public preview writes fail before touching storage',async()=>{const response=await previews(new Request('https://service.test/api/previews',{method:'POST',body:'{}'}),{});assert.equal(response.status,403)});
test('Verified batch is readable without credentials, with Pages CORS; changed fixture hides it',async()=>{const {env,data}=setup();assert.equal((await post(env)).status,200);const req=new Request('https://service.test/api/previews/kadetten/test');let response=await previews(req,env);assert.equal(response.status,200);assert.deepEqual((await response.json()).paragraphs,record.paragraphs);assert.equal(publicReadCors(Response.json({}),req).headers.get('Access-Control-Allow-Origin'),'https://mac-mac-sg.github.io');data.set('kadetten/current.json',{games:[{...game,time:'19:00'}]});assert.equal((await previews(req,env)).status,404)});
test('Invalid content and stale fixtures preserve the saved preview',async()=>{const {env,data}=setup();await post(env);assert.equal((await post(env,{...record,paragraphs:['<script>active content</script>',record.paragraphs[1]]})).status,400);assert.equal((await post(env,{...record,fixtureKey:'wrong'})).status,409);assert.deepEqual(data.get('previews/kadetten/test.json'),record);data.set('kadetten/current.json',{games:[{...game,score:[30,20]}]});assert.equal((await previews(new Request('https://service.test/api/previews/kadetten/test'),env)).status,404)});
