import test from 'node:test';
import assert from 'node:assert/strict';
import {programmes,programmeMatches} from '../server/programmes.mjs';
import {publicReadCors} from '../server/cors.mjs';
const g={id:'izvidac',home:'Kadetten Schaffhausen',away:'HC Izvidac',date:'2026-10-06',time:'18:45'};
const text='Kadetten Schaffhausen vs HC Izvidac 06.10.2026';
const p={id:g.id,fixtureKey:JSON.stringify([g.id,g.home,g.away,g.date,g.time]),sourceUrl:'https://kadettensh.ch/wp-content/downloads/Matchprogramm_Kadetten_EHL.pdf',titlepageText:text,pdfBase64:Buffer.from('%PDF-1.7\n'+'x'.repeat(1100)+'\n%%EOF').toString('base64')};
function setup(){const data=new Map([['kadetten/current.json',{games:[g]}]]),writes=[];return {data,writes,env:{BUCKET:{get:async key=>data.has(key)?{json:async()=>data.get(key),body:data.get(key)}:null,put:async(k,v)=>{writes.push(k);data.set(k,typeof v==='string'?JSON.parse(v):v)}}}}}
async function post(env,body=p){const token='test';env.KADETTEN_UPDATE_KEY_SHA256=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))).toString('hex');return programmes(new Request('https://service.test/api/programmes',{method:'POST',headers:{'X-Kadetten-Update-Key':token},body:JSON.stringify(body)}),env)}
test('Programme requires the right home fixture, opponent and cover date',()=>{assert.equal(programmeMatches(g,text),true);assert.equal(programmeMatches(g,text.replace('06.10.2026','30.09.2026')),false);assert.equal(programmeMatches(g,text.replace('HC Izvidac','CSM Bucuresti')),false);assert.equal(programmeMatches({...g,home:g.away,away:g.home},text),false)});
test('Anonymous programme upload is denied before reading storage',async()=>assert.equal((await programmes(new Request('https://service.test/api/programmes',{method:'POST'}),{})).status,403));
test('Programme is stored by hash, served as PDF with CORS, and hidden on a fixture change',async()=>{const {env,data,writes}=setup();assert.equal((await post(env)).status,200);const req=new Request('https://service.test/api/programmes/izvidac');const metadata=await (await programmes(req,env)).json();assert.match(metadata.pdfPath,/v=[a-f0-9]{64}$/);const pdfReq=new Request('https://service.test'+metadata.pdfPath);const pdf=publicReadCors(await programmes(pdfReq,env),pdfReq);assert.equal(pdf.headers.get('Content-Type'),'application/pdf');assert.equal(pdf.headers.get('Access-Control-Allow-Origin'),'https://mac-mac-sg.github.io');assert.ok((await pdf.text()).startsWith('%PDF-'));assert.equal(writes.length,2);data.set('kadetten/current.json',{games:[{...g,date:'2026-10-07'}]});assert.equal((await programmes(req,env)).status,404);assert.equal(writes.length,2)});
test('Invalid PDF and mismatched programme preserve earlier files',async()=>{const {env,writes}=setup();await post(env);assert.equal((await post(env,{...p,pdfBase64:Buffer.from('not a pdf').toString('base64')})).status,400);assert.equal((await post(env,{...p,titlepageText:'CSM Bucuresti 30.09.2026'})).status,409);assert.equal(writes.length,2)});
